"""first migrate

Revision ID: 0ed0fad4e1c9
Revises: 
Create Date: 2021-06-20 19:38:54.665372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ed0fad4e1c9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=False)
    op.create_table('urls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shorturl', sa.String(length=50), nullable=True),
    sa.Column('longurl', sa.String(length=250), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('click', sa.Integer(), nullable=True),
    sa.Column('user_email', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['user_email'], ['user.email'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_urls_longurl'), 'urls', ['longurl'], unique=True)
    op.create_index(op.f('ix_urls_shorturl'), 'urls', ['shorturl'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_urls_shorturl'), table_name='urls')
    op.drop_index(op.f('ix_urls_longurl'), table_name='urls')
    op.drop_table('urls')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
